# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83528145706174be906ea326d2d28348dc3ea6b1f21ad8234d20ffae7cafa40b08a18241d2a789f2799131961d699007ce05fefaa22dd580d7ef7682d0ba4480

test:
  secret_key_base: 30994295fed245045fd1dbacbc93cdaa29ae44e8cd4973ecbfa5ddca74156c087912589da2fa8af5fb6fb10e610846cbae7651b93bd6e7d627c40b5fbb0c1151

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
